# Generated by Django 5.2.4 on 2025-07-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='background_color',
            field=models.CharField(default='#4A5568', max_length=7),
        ),
    ]
